apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golist-db
  namespace: argocd
spec:
  source:
    helm:
      parameters:
        - name: architecture
          value: "standalone"
        - name: auth.database
          value: "golist"
        - name: auth.username
          value: "golist"
        - name: auth.password
          value: "golist"
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.5.1
  destination:
    namespace: golist
    server: 'https://kubernetes.default.svc'
  project: golist
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
